### ISSUE TITLE
Developer Experience

### ISSUE THREAD

**Issue by ricky-sb** [Access-America/Citizen-Center#105]
I'd like to use this issue to track feedback about our developer experience as a whole. How easy is it to get onboarded and contribute code? What hurdles are new developers facing?  

I'd like to minimize the amount of friction here, even if it means causing extra work on the backend for maintainers. Generating traction is important at this stage, so we should make the DX as pleasant as possible.

**Comment by sarahpowell149** [comment]
I am going to spend some time tomorrow consolidating the information in the various README files. I want everything to be in a single file at the root with a table of contents. During that consolidation effort we can also work on improving the information that lives in the documents.

I'm also going to use myself as a guinea pig for setting up the project from scratch, identifying any areas of friction or points of confusion.

**Comment by sarahpowell149** [comment]
@ricky-sb Can you verify [this ](https://github.com/Access-America/Citizen-Center/commit/738f62609716502f5b246a4e253892d997bec975)commit for me? It looks like some of these are config files and I didn't want to break anything.

**Comment by sarahpowell149** [comment]
@ricky-sb I have finished my first pass at cleaning up the READMEs. The main README now explicitly links to the frontend and backend README files. There is also a table of contents so readers don't feel like they're lost in a sea of markdown.

Can you maybe take a stab at refining the project setup instructions? I don't know how to set it up :) afterwards I can take a look and see if I can find things that need further clarification. Just need the concrete steps to be there first.

**Comment by ricky-sb** [comment]
>Can you maybe take a stab at refining the project setup instructions? I don't know how to set it up :) afterwards I can take a look and see if I can find things that need further clarification. Just need the concrete steps to be there first.

Absolutely! Thanks so much for all the work.
