### ISSUE TITLE
Set up Azure App Service

### ISSUE THREAD

**Issue by ricky-sb** [Access-America/Citizen-Center#12]
We should have our CI/CD automatically deploy FastAPI to App Service.  

Instructions here: https://www.tutlinks.com/deploy-fastapi-on-azure/

**Comment by dboulet01** [comment]
Azure App Service is a different offering than Functions. If we want to be more queue based and event driven, we should stick with Functions. App Service is more traditional container and web hosting - dedicate compute via an App Service Plan. Functions have a consumption based pricing model. Only pay when triggered. Can also leverage dedicated compute with Functions if needed.

**Comment by ricky-sb** [comment]
Sounds good to me. There's probably a specific way we have to do this to
make it compatible with Functions, right?

Like we can't just deploy this to Functions, can we?

**Comment by ricky-sb** [comment]
Actually seems like it supports WSGI, so we just need to integrate it with the code somehow. https://github.com/Azure/azure-functions-python-library/pull/45  

Not exactly sure yet, will do some more research.

**Comment by dboulet01** [comment]
Check these and see if it's something we could use:

https://github.com/Azure/functions-action
https://github.com/Azure/actions-workflow-samples/blob/master/FunctionApp/linux-python-functionapp-on-azure.yml

**Comment by ricky-sb** [comment]
Closing in favor of #53
