### ISSUE TITLE
Remove Nuxt.js dependency

### ISSUE THREAD

**Issue by tarunbod** [Access-America/Citizen-Center#158]
Nuxt.js seems to be adding unnecessary weight to the codebase, contributing to slow reload times, and has a feature set that isn't suited for our applications. We should get rid of it and move to a pure Vue.js frontend, possibly looking at Vue.js 3.0 (https://github.com/vuejs/vue-next/releases/tag/v3.0.0)

**Comment by rmnkbofficial** [comment]
I'll take this one
