### ISSUE TITLE
Link a bank account

### ISSUE THREAD

**Issue by sarah-powell** [Access-America/Citizen-Center#33]
A user should be able to link one or more bank accounts to the portal. This would allow users to easily pay any fees they owe. Any money the citizen is owed by the government could also be wired here.

**Comment by ricky-sb** [comment]
I think a big concern we should address is "auto-pay". I don't really want the government being able to dip their hands in my account at any time. A routing number/account number on file would make it easier to accomplish that.  

Perhaps we should have some intermediary?

**Comment by ricky-sb** [comment]
There may also be some lessons to learn from the [IRS's administration of the EIP](https://www.irs.gov/coronavirus/economic-impact-payments)

**Comment by erichydrick** [comment]
This functionality already largely exists with the government. I can already pay the federal government any taxes owed directly from my bank account or credit card, and I get tax refunds direct deposited when I have those. In the spirit of "let's not hold any data we don't absolutely have to (especially sensitive data)" - I think the best thing to do is to see if we can find an API that lets us pass debit/credit card information to the IRS for payments, or sends the information for a specific transaction. 

Regardless of whether you trust the government to have full-time direct access to all your money, if *we* have that kind of information any possible security breach could be catastrophic.
