### ISSUE TITLE
View government actions

### ISSUE THREAD

**Issue by sarah-powell** [Access-America/Citizen-Center#35]
A user should have access to congressional bills, Supreme Court cases, and other important government proceedings.

**Comment by ricky-sb** [comment]
IMO the dissemination of government information should happen through the press. If you mean like a Press Release section on the website, sure, that's reasonable.  

But to the extent that a user should get their information about government activities solely from a government portal seems a bit iffy.

**Comment by stevecmiller** [comment]
I don't think we should get anything more than the actual bill, ruling on the case, etc. here.  No extraneous information, only what the government actually produces in their action, then rely on the press to help us interpret it and make sense of it

**Comment by ricky-sb** [comment]
How do you decide what information to prioritize? We can't just flood the site with *every* government proceeding (well, we could, but then it wouldn't really be a useful feature 🤣) But we don't really want some bureaucrat curating which government proceedings to publish, right?  

I think there's some value here, we just need to figure out the scope

/cc @stevecmiller
