### ISSUE TITLE
Voting through the portal

### ISSUE THREAD

**Issue by sarah-powell** [Access-America/Citizen-Center#44]
The ability to vote through the portal. Security, privacy, and safety are the most important things to consider here.

In theory, a user could go into the portal, see upcoming and current elections that are being held, click on one, and submit their choice. A confirmation of some kind would be shown to the user so they're affirmed that their vote was recorded.

**Comment by ricky-sb** [comment]
We're not going to have online voting for a *long* time. There's a significant number of hurdles to overcome.  

https://www.verifiedvoting.org/resources/internet-voting/vote-online/  

That being said, I'd like to leave this issue open, because this is something we should work towards.
