### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by ricky-sb** [Access-America/Citizen-Center#5]
Let's set up GitHub Discussions. I'm not exactly sure how to enable it. See here for more info: https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

Sample repository: https://github.com/tailwindlabs/tailwindcss/discussions

**Comment by sarahpowell149** [comment]
Closing in favor of Jira
