### ISSUE TITLE
Create signup component

### ISSUE THREAD

**Issue by ghost** [Access-America/Citizen-Center#69]
The signup frontend component needs to be made. This is separate from the sign in component (#70) but bonus points for making a single component that's reusable for both.
 
[Designs](https://www.figma.com/file/h0KXgHOhxSyttyzsosd2aN/Citizenship-Center?node-id=11%3A50)

Fields:
- First page
   - Email (required)
   - Password (required)
   - (The design says username as well but we aren't doing that. No username is needed)
- Second page
   - First name (required)
   - Middle name
   - Last name (required)
   - (Designs show email address again but this is unnecessary/redundant)
- Third page
   - Zip code, with explanation

**Comment by dboulet01** [comment]
Ref #70 and #72

**Comment by tarunbod** [comment]
>It looks like the only re-usable parts are two input fields (email and password). So it doesn't necessarily make sense to combine these into a single component...right?

That makes sense.

**Comment by dboulet01** [comment]
@tarunbod @ricky-sb lets keep in mind that these fields and functionality will be handled by B2C. we really only need to be concerned with the styling. I have a SPA javascript example working for testing following this tutorial:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-single-page-app?tabs=app-reg-ga

Clone the code in the tutorial and make the updates below:


./JavaScriptSPA/policies.js should look like this:
`// Enter here the user flows and custom policies for your B2C application
// To learn more about user flows, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/user-flow-overview
// To learn more about custom policies, visit https://docs.microsoft.com/en-us/azure/active-directory-b2c/custom-policy-overview

const b2cPolicies = {
    names: {
        signUpSignIn: "B2C_1_sign_up_in",
        forgotPassword: "B2C_1_pass_reset"
    },
    authorities: {
        signUpSignIn: {
            authority: "https://citizencenterus.b2clogin.com/citizencenterus.onmicrosoft.com/B2C_1_sign_up_in",
        },
        forgotPassword: {
            authority: "https://citizencenterus.b2clogin.com/citizencenterus.onmicrosoft.com/B2C_1_pass_reset",
        },
    },
}`

AND
clientID in ./JavaScriptSPA/authConfig.js = "398ff704-9a45-4e3d-8fd4-9d07fadfdbca"

This is just for testing and showing the B2C experience. It can and will be built out further as we define requirements.

**Comment by dboulet01** [comment]
here is a link to documentation for styling the pages:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview

**Comment by ricky-sb** [comment]
Nice find. Looks like there's already a library to integrate it here: https://github.com/mvertopoulos/vue-msal  

I'll do some more research on this. Thanks for the docs @dboulet01

**Comment by dboulet01** [comment]
> I wonder if it's possible to integrate into the [Nuxt Auth module](https://auth.nuxtjs.org/#getting-started), since that comes with some great defaults and user flows.

additional identity providers can be added to B2C without changing code, so it abstracts the authentication from the app a bit which is nice
