### ISSUE TITLE
Create sign in component

### ISSUE THREAD

**Issue by ghost** [Access-America/Citizen-Center#70]
The sign-in page frontend needs to be made. This is separate from the signup page (#69) but bonus points for making a reusable component for both sign in and sign up.
 
[Designs](https://www.figma.com/file/h0KXgHOhxSyttyzsosd2aN/Citizenship-Center?node-id=15%3A98)

Fields:
- Email (username is shown in the designs, but we won't have that field)
- Password

Additional elements to consider
- link to create an account (signup page #69)
- show password button
- ("forgot username" button is shown in the designs, but we won't have that field)
- "forgot password" button
   - This will need to bring in a separate area where someone can type in just their email and have a password reset sent to them.

**Comment by dboulet01** [comment]
User flows in AAD b2c can cover this:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows

Essentially outsource login experience. But still customize the page and styling

**Comment by ricky-sb** [comment]
So short-term we use the hosted UI, long-term we use OAuth @dboulet01?

**Comment by dboulet01** [comment]
> So short-term we use the hosted UI, long-term we use OAuth @dboulet01?

Essentially. Long-term we plugin Login.gov or whatever else we end up using as an IdP within Azure AD B2C. Should require no code changes, just update of the user flow.
