### ISSUE TITLE
Google captcha integration to verify on sign-up

### ISSUE THREAD

**Issue by ghost** [Access-America/Citizen-Center#71]
We'll want to have a captcha presented to the user when they click submit on their sign-up form.

**Comment by ricky-sb** [comment]
There's some privacy concerns with Google's reCAPTCHA service. [See here for more info](https://blog.cloudflare.com/moving-from-recaptcha-to-hcaptcha/)

**Comment by erichydrick** [comment]
I don't see where there was any indication Google was using any data provided for advertising, or really collecting very much), just that people were suspicious of it.

**Comment by ricky-sb** [comment]
Their privacy policy doesn't explicitly disallow data collection. Someone reverse-engineered it when it first came out, they're definitely collecting a lot of data:

https://github.com/toogle/InsideReCaptcha  

> Google servers will receive and process, at least, the following information:
> 
> - Plug-ins
> - User-agent
> - Screen resolution
> - Execution time, timezone
> - Number of click/keyboard/touch actions in the <iframe> of the captcha
> - It tests the behavior of many browser-specific functions and CSS rules
> - It checks the rendering of canvas elements
> - Likely cookies server-side (it's executed on the www.google.com domain)
> - And likely other stuff...
