### ISSUE TITLE
Create profile page

### ISSUE THREAD

**Issue by ghost** [Access-America/Citizen-Center#72]
We need a profile page where a user can see all of the info they have provided. They edit their existing info or provide new info. Things like address are not asked for upon sign-up, but are available in the profile to be saved and re-used.

Designs to come...

**Comment by dboulet01** [comment]
We can leverage Azure AD B2C for user profiles. This is where we can store user information and access it via claims for other app features.

https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows

We can customize the pages and store alongside our other static web files:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview

**Comment by ricky-sb** [comment]
>We can customize the pages and store alongside our other static web files:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview

The static site is gonna be fully decoupled, so we probably won't be able to include our templates directly into B2C. But as long as they act like a standard provider, it shouldn't be a problem at all to integrate. Check this out: https://dev.auth.nuxtjs.org/providers/auth0.html. Notice how there's already boilerplate for a bunch of common providers. We can just integrate B2C using that.  

In fact, someone already did the heavy lifting for us. [Here's an example of B2C + Nuxt (our current tech stack)](https://github.com/jeverduzco/nuxtjs-azure-ad-b2c-login)

**Comment by dboulet01** [comment]
> > We can customize the pages and store alongside our other static web files:
> > https://docs.microsoft.com/en-us/azure/active-directory-b2c/customize-ui-overview
> 
> The static site is gonna be fully decoupled, so we probably won't be able to include our templates directly into B2C. But as long as they act like a standard provider, it shouldn't be a problem at all to integrate. Check this out: https://dev.auth.nuxtjs.org/providers/auth0.html. Notice how there's already boilerplate for a bunch of common providers. We can just integrate B2C using that.
> 
> In fact, someone already did the heavy lifting for us. [Here's an example of B2C + Nuxt (our current tech stack)](https://github.com/jeverduzco/nuxtjs-azure-ad-b2c-login)

B2C needs to reference the custom html for the pages from somewhere (blob storage, etc), so figured we can store the html content in the same storage account as the rest of the front-end. was just a thought
