### ISSUE TITLE
Setup ability to email users

### ISSUE THREAD

**Issue by ghost** [Access-America/Citizen-Center#73]
There are many times when we want to email users. 

- Confirmation email when they signup
- Forgot password emails
- Important information and announcements
- Any additional announcements or "newsletters" they have signed up for

We need the ability to send an email to a user.

**Comment by erichydrick** [comment]
Does Azure have something similar to Amazon's SES? If so we could set up a serverless function to send the actual email and then just have the backend trigger it on the appropriate condition (signup, click the "Forgot password" button, etc.).

**Comment by dboulet01** [comment]
We can use the Send Grid API to send emails

**Comment by erichydrick** [comment]
@dboulet01 Would we be using the SendGrid API to manage subscribers, lists, etc. or just power the email sends? It sounds like we could get a nice slew of tickets around email integration and management.

**Comment by erichydrick** [comment]
We're going to need an API key, and I'm curious about how to do this so the organization key isn't exposed but we're still able to do a proper test (writing a unit test against a mock SendGrid server only gets us so far, it'd be nice to trigger a test message and confirm it appears in an email account).

**Comment by erichydrick** [comment]
But it looks like a serverless function that takes in a message JSON and makes this call is what we want:

https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

It doesn't even have to match SendGrid's message JSON. As long as it has the basics (to, from, subject, template, personalization data) the function can build the proper request body so the only piece of code that needs to know anything about how the SendGrid API woks is the event handler actually interacting with SendGrid.

**Comment by erichydrick** [comment]
So a few questions for this ticket - are we using a template or will the emails be plain text/HTML content? Are we going to use an HTML endpoint to trigger these (accessible only internally by the app I'm assuming), or some other trigger type. If it's other I'll likely need some help setting the function up in serverless.yml, or we'll need another way to test these functions locally.

**Comment by ricky-sb** [comment]
>Are we using a template or will the emails be plain text/HTML content?   
Currently, we don't have any designs. I'd like to use a template. @mbass99, can you look into this?  


>Are we going to use an HTML endpoint to trigger these (accessible only internally by the app I'm assuming)
HTTP endpoint? Yeah. I'd prefer that over SMTP. SendGrid's API is pretty nice

**Comment by ricky-sb** [comment]
> But it looks like a serverless function that takes in a message JSON and makes this call is what we want:
> 
> https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html
> 
> It doesn't even have to match SendGrid's message JSON. As long as it has the basics (to, from, subject, template, personalization data) the function can build the proper request body so the only piece of code that needs to know anything about how the SendGrid API woks is the event handler actually interacting with SendGrid.

[They have an SDK to simplify this](https://sendgrid.com/docs/for-developers/sending-email/v3-python-code-example/)  

```python
# using SendGrid's Python Library
# https://github.com/sendgrid/sendgrid-python
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

message = Mail(
    from_email='from_email@example.com',
    to_emails='to@example.com',
    subject='Sending with Twilio SendGrid is Fun',
    html_content='<strong>and easy to do anywhere, even with Python</strong>')
try:
    sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
    response = sg.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except Exception as e:
    print(e.message)
```  

This [along with Handlebars templates](https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/) should simplify things a bit.

**Comment by erichydrick** [comment]
I don't think I was clear in my HTTP trigger question - I was referring the how we trigger the serverless function to call the Sendgrid API and actually send the email. Based on the comments here, it sounds like we're going to build this message using a template and building personalization objects to populate that template's data for all recipients. I can try to find time in the next few days to get cracking on that unless anyone can get going sooner.

**Comment by mbass99** [comment]
> > Are we using a template or will the emails be plain text/HTML content?
> 
> Currently, we don't have any designs. I'd like to use a template. @mbass99, can you look into this?
> 
> > Are we going to use an HTML endpoint to trigger these (accessible only internally by the app I'm assuming)
> 
> HTTP endpoint? Yeah. I'd prefer that over SMTP. SendGrid's API is pretty nice

**Comment by mbass99** [comment]
> > > Are we using a template or will the emails be plain text/HTML content?
> > 
> > 
> > Currently, we don't have any designs. I'd like to use a template. @mbass99, can you look into this?
@ricky-sb are you just talking about emails coming from the app?  
> > > Are we going to use an HTML endpoint to trigger these (accessible only internally by the app I'm assuming)
> > 
> > 
> > HTTP endpoint? Yeah. I'd prefer that over SMTP. SendGrid's API is pretty nice

**Comment by ricky-sb** [comment]
>I was referring the how we trigger the serverless function to call the Sendgrid API and actually send the email  

@erichydrick, Ah sorry, I understand now. For the transactional-type emails, we could trigger it on the API call to `/account/reset` or `account/confirm`  

For the newsletters/updates, we'd probably trigger it when we "publish" a new post?

>it sounds like we're going to build this message using a template and building personalization objects to populate that template's data for all recipients. I can try to find time in the next few days to get cracking on that unless anyone can get going sooner.

Yes sir, I'd love for you to take a first crack at it. I'll make sure to get you an API key (#86) so you're not blocked.    

----

>@ricky-sb are you just talking about emails coming from the app?

@mbass99, yep, that's right. For transactional-type emails, like "Confirm Account", or "Forgot Password", I'd love to use some sort of template. For now it could be some default template, but eventually I'd love to get some custom design done.

**Comment by erichydrick** [comment]
So the Serverless framework is really starting to show its limitations on this issue. It seems to work fine in Azure for setting up a RESTful API, but for something like sending an email that should really be event-driven, ti doesn't seem to work well. I mostly used it to start with because it offered a way to test API endpoints locally, but doesn't anyone know a good way to test Azure functions locally outside of Serverless framework? I've seen the VS Code extension, but I don't want to dictate an IDE extension as the only way a developer can test stuff.

**Comment by ricky-sb** [comment]
We don't need a VS Code extension to test the Serverless functions, do we? I've been using PyCharm and the [Serverless CLI](https://www.serverless.com/framework/docs/providers/azure/cli-reference/invoke/)  

> It seems to work fine in Azure for setting up a RESTful API, but for something like sending an email that should really be event-driven, ti doesn't seem to work well.

Isn't this where Lambda functions shine? Event-driven nature? What event(s) should trigger the sending of an email?

**Comment by dboulet01** [comment]
You can trigger functions different ways. I think using storage queues to trigger would work.

In terms of Serverless Framework, looks like it supports queue triggers:
https://www.serverless.com/framework/docs/providers/azure/events/queuestorage/

Here are also a few ways to setup AzFunctions locally for testing:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-local

**Comment by erichydrick** [comment]
> We don't need a VS Code extension to test the Serverless functions, do we? I've been using PyCharm and the [Serverless CLI](https://www.serverless.com/framework/docs/providers/azure/cli-reference/invoke/)
> 
> > It seems to work fine in Azure for setting up a RESTful API, but for something like sending an email that should really be event-driven, ti doesn't seem to work well.
> 
> Isn't this where Lambda functions shine? Event-driven nature? What event(s) should trigger the sending of an email?

I was using EventGrid, which doesn't have good Lambda support. Sending events into a queue would work, that's just 1 more cloud service we have to pay for, although it does give the portal some resiliency if emailing is down for any reason (SendGrid outage, or we just need to disable that part of the portal for maintenance).

**Comment by dboulet01** [comment]
queues are part of storage accounts which is a requirement for Azure Functions. queues are extremely low cost

pricing:
https://azure.microsoft.com/en-us/pricing/details/storage/queues/

docs:
https://docs.microsoft.com/en-us/azure/storage/queues/storage-queues-introduction
